
# https://docs.python.org/3/library/dis.html#python-bytecode-instructions


import os, json
os_join = os.path.join
THISDIR = os.path.realpath(os.path.dirname(__file__))

NAMES = [
	'RETURN',
]

def gen():

	INDENT = '\t'

	yield '/* this file auto-generated by {} */\n\n'.format(os.path.basename(__file__))

	yield '#ifndef __SNAP_STD_OPS_H__\n'
	yield '#define __SNAP_STD_OPS_H__\n\n'

	yield '#include "snap/snap_api.h"\n\n'

	for name in NAMES:

		yield 'void SNAP_STD_OP__' + name + '(SnapObject* ENV){\n\n'

		if name == 'RETURN':

			yield INDENT + '/* TODO: RETURN */\n'

		yield '}\n\n'

	yield '#endif /* __SNAP_STD_OPS_H__ */\n'

if __name__ == '__main__':

	with open(os.path.join(THISDIR, 'snap_std_ops.h'), 'w') as openfile:
		openfile.write(''.join(list(gen())))

