/* this file auto-generated by gen_std_ops.py */

#ifndef __SNAP_STD_OPS_H__
#define __SNAP_STD_OPS_H__

#include "snap/snap_api.h"

void SNAP_STD_OP__RETURN(SnapObject* ENV){

	/* TODO: RETURN */
}

#endif /* __SNAP_STD_OPS_H__ */
