
# https://www.python.org/downloads/release/python-3123/
# 	-- ../Python/bytecodes.c
# https://docs.python.org/3/library/dis.html#python-bytecode-instructions

import os, json
os_join = os.path.join
THISDIR = os.path.realpath(os.path.dirname(__file__))

OPCODES_FILEPATH = os_join(THISDIR, 'py_opcodes.json')
assert os.path.exists(OPCODES_FILEPATH), 'missing py_opcodes.json file'

def gen():

	INDENT = '\t'

	yield '/* this file auto-generated by {} */\n\n'.format(os.path.basename(__file__))

	yield '#ifndef __SNAP_PY_OPS_H__\n'
	yield '#define __SNAP_PY_OPS_H__\n\n'

	yield '#include "snap/snap_api.h"\n\n'

	with open(OPCODES_FILEPATH, 'r') as openfile:
		data = json.loads(openfile.read())

	for entry in data['entries']:

		yield 'void SNAP_PY_OP__' + entry['name'] + '(SnapObject* ENV){\n\n'

		yield INDENT + '/* ' + entry['text'] + ' */\n'

		yield '}\n\n'

	yield '#endif /* __SNAP_PY_OPS_H__ */\n'

if __name__ == '__main__':

	with open('snap_py_ops.h', 'w') as openfile:
		openfile.write(''.join(list(gen())))

