/*this file autogenerated by gen_args.py*/

#ifndef __SNAP_ARGS_H__
#define __SNAP_ARGS_H__

#include "snap/snap_core.h"

SnapObject_t* _a1(SnapObject_t* ENV, SnapObject_t* ARG0){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k1(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a2(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k2(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a3(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k3(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a4(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k4(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a5(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k5(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a6(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k6(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a7(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k7(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a8(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k8(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a9(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k9(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a10(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k10(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a11(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k11(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a12(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k12(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a13(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k13(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a14(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k14(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a15(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13, SnapObject_t* ARG14){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k15(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13, SnapObject_t* KEY14, SnapObject_t* VALUE14){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a16(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13, SnapObject_t* ARG14, SnapObject_t* ARG15){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k16(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13, SnapObject_t* KEY14, SnapObject_t* VALUE14, SnapObject_t* KEY15, SnapObject_t* VALUE15){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a17(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13, SnapObject_t* ARG14, SnapObject_t* ARG15, SnapObject_t* ARG16){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k17(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13, SnapObject_t* KEY14, SnapObject_t* VALUE14, SnapObject_t* KEY15, SnapObject_t* VALUE15, SnapObject_t* KEY16, SnapObject_t* VALUE16){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a18(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13, SnapObject_t* ARG14, SnapObject_t* ARG15, SnapObject_t* ARG16, SnapObject_t* ARG17){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k18(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13, SnapObject_t* KEY14, SnapObject_t* VALUE14, SnapObject_t* KEY15, SnapObject_t* VALUE15, SnapObject_t* KEY16, SnapObject_t* VALUE16, SnapObject_t* KEY17, SnapObject_t* VALUE17){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a19(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13, SnapObject_t* ARG14, SnapObject_t* ARG15, SnapObject_t* ARG16, SnapObject_t* ARG17, SnapObject_t* ARG18){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k19(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13, SnapObject_t* KEY14, SnapObject_t* VALUE14, SnapObject_t* KEY15, SnapObject_t* VALUE15, SnapObject_t* KEY16, SnapObject_t* VALUE16, SnapObject_t* KEY17, SnapObject_t* VALUE17, SnapObject_t* KEY18, SnapObject_t* VALUE18){
	/*TODO*/
	return NULL;
}

SnapObject_t* _a20(SnapObject_t* ENV, SnapObject_t* ARG0, SnapObject_t* ARG1, SnapObject_t* ARG2, SnapObject_t* ARG3, SnapObject_t* ARG4, SnapObject_t* ARG5, SnapObject_t* ARG6, SnapObject_t* ARG7, SnapObject_t* ARG8, SnapObject_t* ARG9, SnapObject_t* ARG10, SnapObject_t* ARG11, SnapObject_t* ARG12, SnapObject_t* ARG13, SnapObject_t* ARG14, SnapObject_t* ARG15, SnapObject_t* ARG16, SnapObject_t* ARG17, SnapObject_t* ARG18, SnapObject_t* ARG19){
	/*TODO*/
	return NULL;
}

SnapObject_t* _k20(SnapObject_t* ENV, SnapObject_t* KEY0, SnapObject_t* VALUE0, SnapObject_t* KEY1, SnapObject_t* VALUE1, SnapObject_t* KEY2, SnapObject_t* VALUE2, SnapObject_t* KEY3, SnapObject_t* VALUE3, SnapObject_t* KEY4, SnapObject_t* VALUE4, SnapObject_t* KEY5, SnapObject_t* VALUE5, SnapObject_t* KEY6, SnapObject_t* VALUE6, SnapObject_t* KEY7, SnapObject_t* VALUE7, SnapObject_t* KEY8, SnapObject_t* VALUE8, SnapObject_t* KEY9, SnapObject_t* VALUE9, SnapObject_t* KEY10, SnapObject_t* VALUE10, SnapObject_t* KEY11, SnapObject_t* VALUE11, SnapObject_t* KEY12, SnapObject_t* VALUE12, SnapObject_t* KEY13, SnapObject_t* VALUE13, SnapObject_t* KEY14, SnapObject_t* VALUE14, SnapObject_t* KEY15, SnapObject_t* VALUE15, SnapObject_t* KEY16, SnapObject_t* VALUE16, SnapObject_t* KEY17, SnapObject_t* VALUE17, SnapObject_t* KEY18, SnapObject_t* VALUE18, SnapObject_t* KEY19, SnapObject_t* VALUE19){
	/*TODO*/
	return NULL;
}

#endif /* __SNAP_ARGS_H__ */
