
import os

THISDIR = os.path.realpath(os.path.dirname(__file__))

COUNT = 20
def gen():

	yield '/*this file autogenerated by {}*/\n'.format(os.path.basename(__file__))
	yield '\n'
	yield '#ifndef __SNAP_ARGS_H__\n'
	yield '#define __SNAP_ARGS_H__\n\n'

	yield '#include "snap/snap_core.h"\n'

	yield '\n'

	i = 0
	while i < COUNT:
		i += 1

		argset = ', '.join(['SnapObject_t* ARG' + str(num) for num in range(i)])

		yield 'SnapObject_t* _a' + str(i) + '(SnapObject_t* ENV, ' + argset + '){\n'
		yield '\t/*TODO*/\n'
		yield '\treturn NULL;\n'
		yield '}\n\n'

		kwargset = ', '.join(['SnapObject_t* KEY' + str(num) + ', SnapObject_t* VALUE' + str(num) for num in range(i)])
		yield 'SnapObject_t* _k' + str(i) + '(SnapObject_t* ENV, ' + kwargset + '){\n'
		yield '\t/*TODO*/\n'
		yield '\treturn NULL;\n'
		yield '}\n\n'

	yield '#endif /* __SNAP_ARGS_H__ */\n'

def gen_msg():

	yield '/*this file autogenerated by {}*/\n'.format(os.path.basename(__file__))
	yield '\n'
	yield '#ifndef __SNAP_MSG_H__\n'
	yield '#define __SNAP_MSG_H__\n\n'

	yield '#include "snap/snap_core.h"\n'

	yield 'SnapObject_t* __msg(SnapObject_t* ENV, SnapObject_t* ARGS, SnapObject_t* UNPACK_ARGS, SnapObject_t* KWARGS, SnapObject_t* UNPACK_KWARGS){\n'
	
	yield '\n\t/* TODO make new message from args, register with ENV gc, and return it */\n\n'

	yield '\treturn NULL;\n'
	yield '}\n'

	#yield '#define _msg(ARGS, UNPACK_ARGS, KWARGS, UNPACK_KWARGS) __msg(ENV, ARGS, UNPACK_ARGS, KWARGS, UNPACK_KWARGS)\n'

	# denote with:
	# a = args, A = unpack_args, k = kwargs, K = unpack_kwargs

	positions = ['a','A','k','K']

	types = dict(
		a='ARGS',
		A='UNPACK_ARGS',
		k='KWARGS',
		K='UNPACK_KWARGS',
		)

	# use binary numbers to make this quick and easy
	for i in range(2 ** 4):

		num = bin(i)[2:].zfill(4)

		ones = num.count('1')

		selection = [positions[idx] if num[idx] == '1' else None for idx in range(len(num))]

		msg_name = '_msg_' + ''.join([s for s in selection if isinstance(s, str)])
		if msg_name.endswith('_'):
			msg_name = msg_name[:-1]

		use_args = ', '.join([types[s] if isinstance(s, str) else 'NULL' for s in selection])
		decl_args = ', '.join([types[s] for s in selection if isinstance(s, str)])

		yield '#define ' + msg_name + '(' + decl_args + ') __msg(ENV, ' + use_args + ')\n\n'

	yield '\n\n'

	yield '/* TODO: define SnapMessage class and unpack method */\n\n'

	yield '#endif /* __SNAP_MSG_H__ */\n'

if __name__ == '__main__':

	with open(os.path.join(THISDIR, 'snap_args.h'), 'w') as openfile:
		for s in gen():
			openfile.write(s)

	with open(os.path.join(THISDIR, 'snap_msg.h'), 'w') as openfile:
		for s in gen_msg():
			openfile.write(s)

