/*this file autogenerated by gen_args.py*/

#ifndef __SNAP_MSG_H__
#define __SNAP_MSG_H__

#include "snap/snap_core.h"
SnapObject_t* __msg(SnapObject_t* ENV, SnapObject_t* ARGS, SnapObject_t* UNPACK_ARGS, SnapObject_t* KWARGS, SnapObject_t* UNPACK_KWARGS){

	/* TODO make new message from args, register with ENV gc, and return it */

	return NULL;
}
#define _msg() __msg(ENV, NULL, NULL, NULL, NULL)

#define _msg_K(UNPACK_KWARGS) __msg(ENV, NULL, NULL, NULL, UNPACK_KWARGS)

#define _msg_k(KWARGS) __msg(ENV, NULL, NULL, KWARGS, NULL)

#define _msg_kK(KWARGS, UNPACK_KWARGS) __msg(ENV, NULL, NULL, KWARGS, UNPACK_KWARGS)

#define _msg_A(UNPACK_ARGS) __msg(ENV, NULL, UNPACK_ARGS, NULL, NULL)

#define _msg_AK(UNPACK_ARGS, UNPACK_KWARGS) __msg(ENV, NULL, UNPACK_ARGS, NULL, UNPACK_KWARGS)

#define _msg_Ak(UNPACK_ARGS, KWARGS) __msg(ENV, NULL, UNPACK_ARGS, KWARGS, NULL)

#define _msg_AkK(UNPACK_ARGS, KWARGS, UNPACK_KWARGS) __msg(ENV, NULL, UNPACK_ARGS, KWARGS, UNPACK_KWARGS)

#define _msg_a(ARGS) __msg(ENV, ARGS, NULL, NULL, NULL)

#define _msg_aK(ARGS, UNPACK_KWARGS) __msg(ENV, ARGS, NULL, NULL, UNPACK_KWARGS)

#define _msg_ak(ARGS, KWARGS) __msg(ENV, ARGS, NULL, KWARGS, NULL)

#define _msg_akK(ARGS, KWARGS, UNPACK_KWARGS) __msg(ENV, ARGS, NULL, KWARGS, UNPACK_KWARGS)

#define _msg_aA(ARGS, UNPACK_ARGS) __msg(ENV, ARGS, UNPACK_ARGS, NULL, NULL)

#define _msg_aAK(ARGS, UNPACK_ARGS, UNPACK_KWARGS) __msg(ENV, ARGS, UNPACK_ARGS, NULL, UNPACK_KWARGS)

#define _msg_aAk(ARGS, UNPACK_ARGS, KWARGS) __msg(ENV, ARGS, UNPACK_ARGS, KWARGS, NULL)

#define _msg_aAkK(ARGS, UNPACK_ARGS, KWARGS, UNPACK_KWARGS) __msg(ENV, ARGS, UNPACK_ARGS, KWARGS, UNPACK_KWARGS)



/* TODO: define SnapMessage class and unpack method */

#endif /* __SNAP_MSG_H__ */
